services:
  app:
    build:
      context: .
      args:
        - DEV=true
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=recipe_app_db_dev
      - DB_USER=postgres
      - DB_PASSWORD=changeme
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:17-alpine3.22
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: recipe_app_db_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d my_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dev-db-data: